version: '3.8'

services:
  # FastAPI 애플리케이션 (프로덕션용)
  app:
    build: .
    ports:
      - "8002:8002"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=purchase_dashboard
      - ENV=production
    depends_on:
      - mongodb
    restart: always
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # MongoDB 데이터베이스
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-password123}
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Nginx 리버스 프록시
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: always
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge
